_target_: src.model.TTSModel
melspec_generator:
  _target_: src.model.FastSpeech2
wav_generator:
  _target_: src.model.HiFiGAN
  input_dim: 80
  hidden_dim: 512
  relu_constant: 0.1
  transposed_kernels: [16, 16, 4, 4]
  mrf_kernels: [3, 7, 11]
  dilations: [[[1, 1], [3, 1], [5, 1]], [[1, 1], [3, 1], [5, 1]], [[1, 1], [3, 1], [5, 1]]]
