_target_: src.model.TTSModel
melspec_generator:
  _target_: src.model.MelSpectrogram
  sr: 22050
  win_length: 1024
  hop_length: 256
  n_fft: 1024
  f_min: 0
  f_max: 8000
  n_mels: 80
  power: 1.0
  pad_value: -11.5129251 # value of melspectrograms if we fed a silence into `MelSpectrogram`
wav_generator:
  _target_: src.model.HiFiGAN
  input_dim: 80
  hidden_dim: 512
  transposed_kernels: [16, 16, 4, 4]
  mrf_kernels: [3, 7, 11]
  dilations: [[[1, 1], [3, 1], [5, 1]], [[1, 1], [3, 1], [5, 1]], [[1, 1], [3, 1], [5, 1]]]
