_target_: src.logger.CometMLWriter
project_name: "HiFiGAN"
workspace: null
run_name: "testing"
mode: "online"
loss_names: ["loss_disc", "loss_gen", "loss_adv", "loss_fm", "loss_mel"] # which losses to log (useful for multi-loss tasks, s.a. GANs)
log_checkpoints: False # set to True if you want to log save_dir with checkpoints to W&B
id_length: 32 # length of the run_id
